export const whiteList = [
  // 'ElInput',
  // 'ElDatePicker',
  // 'ElButton',
  // 'ElForm',
  // 'ElFormItem',
  // 'ElTable',
  // 'ElTableColumn',
  'TinyCarouselItem',
  'TinyCarousel',
  'a',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'p',
  'ol',
  'ul',
  'li',
  'input',
  'video',
  'Img',
  // 'button',
  // 'table',
  // 'td',
  // 'form',
  'label',
  // 'TinyButtonGroup',
  'TinyRow',
  'TinyLayout',
  'TinyForm',
  'TinyFormItem',
  'TinyCol',
  'TinyButton',
  'TinyInput',
  'TinyRadio',
  'TinyRadioGroup',
  'TinySelect',
  'TinySwitch',
  'TinySearch',
  'TinyCheckbox',
  'TinyCheckboxButton',
  'TinyCheckboxGroup',
  // 'TinyDialogBox',
  'TinyTabs',
  'TinyTabItem',
  // 'ActionButton',
  // 'TinyBreadcrumb',
  // 'TinyBreadcrumbItem',
  // 'TinyCollapse',
  // 'TinyCollapseItem',
  'TinyGrid',
  'TinyCard',
  // 'TinyGridColumn',
  'TinyPager',
  // 'TinyPopeditor',
  'TinyTree',
  // 'TinyTimeLine',
  // 'TinyTooltip',
  // 'TinyPopover',
  'TinyDatePicker',
  'TinyNumeric',
  'TinyTransfer',
  'div',
  'Slot',
  // 'RouterView',
  // 'RouterLink',
  // 'Collection',
  'Text',
  'Icon',
  'TinyChartPie',
  'TinyChartLine',
  'TinyChartHistogram',
  'TinyChartBar',
  'TinyChartRadar',
  'TinyChartRing',
  // 'GridStack',
  // 'GridStackItem'
];

export const miniWhiteList = [
  'a',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'p',
  'ol',
  'ul',
  'li',
  'div',
  'input',
  'video',
  'label',
  'Img',
  "Slot",
  'Text',
  'TinyForm',
  'TinyFormItem',
  'TinyButton',
  'TinyInput',
  'TinyRadio',
  'TinyRadioGroup',
  'TinySelect',
  'TinySwitch',
  'TinyNumeric',
  'TinyCheckbox',
  'TinyCheckboxButton',
  'TinyCheckboxGroup',
  'TinyDatePicker',
  'TinyGrid',
  'TinyCard',
];

const PLUS_ONLY_COMPONENTS = [
  'TinyCarouselItem',
  'TinyCarousel',
  'TinyPager',
  'TinyTree',
  'TinyTransfer',
] as const;

export const standardWhiteList = whiteList.filter(
  (name) => !PLUS_ONLY_COMPONENTS.includes(name as (typeof PLUS_ONLY_COMPONENTS)[number]),
);